### ISSUE TITLE
Meta: Linux Mint Troubleshooting Guide is outdated

### ISSUE THREAD

**Issue by WhosyVox** [linuxmint/mint20.3-beta#1]
The page below only mentions LMDE3 and Linux Mint 18 when referring to the Ubuntu/Debian base for Mint.
Considering we're now past Mint 19 and near the end of Mint 20, perhaps this ought be updated.

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/where.html#upstream-bugs-launchpad-and-debbugs

**Comment by clefebvre** [comment]
Removed by https://github.com/linuxmint/doc-troubleshooting-guide/commit/0a376e6c2aa32b12f463ae5d2f309056246eda61
