### ISSUE TITLE
mint-themes-legacy: mint-y-dark metacity theme is missing

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mint20.3-beta#10]
https://github.com/linuxmint/mint-themes-legacy/issues/1

**Comment by Harry-W-Haines-III** [comment]
Some of the metacity folders and XML files seem to be missing in the mint-themes-legacy_1.8.9_all.deb package.

**Comment by enigma131** [comment]
... but at least 1white one must be keeped

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mint-themes-legacy/commit/e86a214d959ffca2222c73da0676e8510432a3fe fixed in 1.9.0.
