### ISSUE TITLE
webapp-manager: When searching for icons online, the images displayed appear in a very small space.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#11]
webapp-manager 1.1.7

Steps to reproduce:

1- Open Web Apps
2- Add a web page
3- Click on the button 'Find icons online'.

![wp1](https://user-images.githubusercontent.com/68134588/145697119-0beebadb-b77a-4dc5-880c-2a7108bd5b7d.png)

![wp2](https://user-images.githubusercontent.com/68134588/145697121-fe817877-f44e-4d4d-b2a0-7b64398c9157.png)

> mint@mint:~$ cannot identify image file <_io.BytesIO object at 0x7fd5def5f1d0>
https://github.githubassets.com/favicons/favicon.svg
cannot identify image file <_io.BytesIO object at 0x7fd5d8f7ce50>
https://github.githubassets.com/pinned-octocat.svg

I checked in version 1.1.5 with the same parameters and the bug does not occur:
![ww](https://user-images.githubusercontent.com/68134588/145697282-93c6a3c9-6c28-4310-9ef9-06194b785557.png)

> h2gn@h2gn:~$ cannot identify image file <_io.BytesIO object at 0x7f61c19e9270>
https://github.githubassets.com/favicons/favicon.svg
cannot identify image file <_io.BytesIO object at 0x7f61c19e9270>
https://github.githubassets.com/pinned-octocat.svg

**Comment by WhosyVox** [comment]
Issue looks like it's resolved from switching the expand property to `True` at line 524 of `/usr/share/webapp-manager/webapp-manager.UI`
I have no idea how to add that as a commit..

**Comment by LinuxOnTheDesktop** [comment]
@WhosyVox 

> I have no idea how to add that as a commit.

I _think_ the steps are as follows.

1. Using Git (the 'git' command-line tool) or else Gitub: fork https://github.com/linuxmint/webapp-manager. (If you use Git, you will need to have set up a local version of https://github.com/linuxmint/webapp-manager.)
2. Using Git or Gitub: within the fork, create a new 'branch'.
3. Using your local device or Gitub: make the change to the 'UI' file (and, if using local device, ensure that you 'commit' the change).
4. Using Git or Gitub: send a 'pull [in]' request to https://github.com/linuxmint/webapp-manager. (This has steps of its own . .)

**Comment by clefebvre** [comment]
Fixed in webapp-manager 1.1.8
