### ISSUE TITLE
iso: Memtest is outdated

### ISSUE THREAD

**Issue by vikingsmurf** [linuxmint/mint20.3-beta#12]
Hello, the includet Memtest68+ 5.01 didn´t work from the bootable Linux USB drive, it was freezing everytime during the test in the first few seconds. 
I´ve checked the memtest website and there I found, that the included Memtest Version 5.01 is from 2013. 

The latest Version Memtest68+ 5.31b was working fine after burning it to a bootable USB drive just by itself. 

Maybe you can consider to update the Memtest68+ to the latest Version in the next released Linux Image.
That would be a great help!

Thank you and best regards.

**Comment by Fantu** [comment]
memtest86+ package on debian is orphan, packaging is also very old, I started to update packaging (https://salsa.debian.org/debian/memtest86plus/-/merge_requests/1 I keep debhelper 12 and tested on it so can be directly used also on mint backports if needed waiting new official build on next debian/ubuntu), I'll try to update to 5.31b but I don't know if I'll have enough time to adapt and fix multiboot and some other things, any help will be appreciate

**Comment by clefebvre** [comment]
According to upstream this isn't ready for production yet:

![image](https://user-images.githubusercontent.com/1138515/146580049-88b84136-2776-466f-9dd9-a217fa4bdde9.png)

It should be marked as stable upstream.

**Comment by Fantu** [comment]
I used memtest86+ many times and in latest years I saw 5.01 inusable or not working correctly on major of recent system :(
I started to work on 5.31b packages as wrote with more detail here: https://forums.debian.net/viewtopic.php?f=19&t=150987
if someone want help me to test and improve it are welcome
