### ISSUE TITLE
gnome-calendar: crashes when re/activating an option in Manage calendars

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#13]
The 'Birthdays and Anniversaries' option is [not available](https://user-images.githubusercontent.com/68134588/145721128-138bd117-4095-470c-b17e-44c594af21eb.png) as calendar in gnome-calendar. When going to the '[Manage Calendars](https://user-images.githubusercontent.com/68134588/145721172-7ac81be2-30b4-45f0-9806-f5c3ec6e12ab.png)' option and [disabling and re-enabling](https://user-images.githubusercontent.com/68134588/145721188-2298d5fe-6fa5-4b0e-bb47-b8fa8a52dbb9.png) the 'Birthdays and Anniversaries' or 'Personal' buttons, gnome-calendar crashes.

Step to reproduce:

1- open gnome-calendar
2- open the option 'Manage calendars'
3- change the active/inactive status in the toggle buton in the 'Birthdays and Anniversaries' or 'Personal' options. 

---
mint@mint:~$ gnome-calendar
GWeather-Message: 14:22:18.918: Failed to get Yr.no forecast data: 404 Not Found

**
GcalTimeline:ERROR:../src/core/gcal-timeline.c:212:increase_completed_calendars: assertion failed: (self->completed_calendars <= g_hash_table_size (self->calendars))
Bail out! GcalTimeline:ERROR:../src/core/gcal-timeline.c:212:increase_completed_calendars: assertion failed: (self->completed_calendars <= g_hash_table_size (self->calendars))
Aborted (core dumped)

---
[logs.zip](https://github.com/linuxmint/mint20.3-beta/files/7699135/logs.zip)

P.S. I checked the flatpak version and it does not have these problems (it also allows you to see the weather forecast correctly). I installed gnome-contacts thinking it would solve the problem with the 'Birthdays and Anniversaries' option but the problem persisted.

**Comment by WhosyVox** [comment]
I've actually just replicated this in Mint 20.2 as they use the same package. This does not appear to be a new bug.

Unchecking any number calendars and then re-checking one will trigger this crash.

**Comment by mtwebster** [comment]
This looks to be an issue in gnome-calendar: https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues/674

The flatpak version is bleeding edge so it's possible there are potentially other factors contributing to the different behavior.

**Comment by mtwebster** [comment]
fixed by: https://gitlab.com/linuxmint/pins/mint/gnome-calendar/-/commit/bfb794135bbfa2d38360f7b238096e8d60118a8a
