### ISSUE TITLE
Meta issue: This Mint 20.3-beta is not advertised on the main website, blog, or Facebook

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint20.3-beta#14]
I was expecting to see this Mint 20.3-beta announced somewhere, with download links, but i didn't see it anywhere... Not on the main website, not on the blogs, not on Facebook.

PROS: You won't get too much bug reports. :)
CONS: Bugs won't get fixed. :(

**Comment by SebastJava** [comment]
...And it is also missing on the https://forums.linuxmint.com/viewforum.php?f=143

**Comment by Harry-W-Haines-III** [comment]
Clem usually waits until all the mirrors have it before a formal announcement.  It will probably be announced on Monday, Dec 12.

**Comment by SebastJava** [comment]
Done.
