### ISSUE TITLE
website: favicon is wrong on search engines

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#15]
Unless it is done on purpose, apparently the [new website](https://www.linuxmint.com/searchengines.php) changed the favicons.  Once the search engine has been added the icon is displayed correctly. 

![google engine apear with LM logo](https://user-images.githubusercontent.com/68134588/145724646-49f7638f-974c-45ee-9d07-1607f9a6994f.png)

**Comment by clefebvre** [comment]
Fixed.
