### ISSUE TITLE
Graphics driver not working on Acer Nitro 5 with AMD Ryzen 7 5800H

### ISSUE THREAD

**Issue by MortenPiil** [linuxmint/mint20.3-beta#16]
Hi, I have to use Kubuntu on this machine - but I would really like to get back to Mint.
The machine is about a half year old and I could not get Mint to enable the amdgpu driver. Kubuntu 21.04 recognizes the graphics HW immediately.
I've booted the new 20.3 BETA and have run inxi -G with the following output:
Graphics:
  Device-1: NVIDIA driver: N/A 
  Device-2: AMD driver: N/A 
  Display: x11 server: X.Org 1.20.11 driver: ati,fbdev 
  unloaded: modesetting,radeon,vesa resolution: 1920x1080~77Hz 
  OpenGL: renderer: llvmpipe (LLVM 12.0.0 256 bits) v: 4.5 Mesa 21.0.3 

With Kubuntu I get this output:
inxi -G
Graphics:  Device-1: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: N/A 
           Device-2: AMD Cezanne driver: amdgpu v: kernel 
           Device-3: Quanta HD User Facing type: USB driver: uvcvideo 
           Display: x11 server: X.Org 1.20.11 driver: loaded: amdgpu,ati unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~144Hz 
           OpenGL: renderer: AMD RENOIR (DRM 3.40.0 5.11.0-41-generic LLVM 12.0.0) v: 4.6 Mesa 21.0.3 

Here's the output of dmesg and lspci when running on Mint 20.3 BETA
[dmesg.txt](https://github.com/linuxmint/mint20.3-beta/files/7713808/dmesg.txt)
[lspci.txt](https://github.com/linuxmint/mint20.3-beta/files/7713809/lspci.txt)

I'm quite ready to do more tests to get Mint running.
BTW: my brother uses a Lenovo with a Ryzen 4700 and have the same problem.
Hopefully
Morten

**Comment by WhosyVox** [comment]
Not an issue with the beta; the drivers/kernel/base is shared with Ubuntu 20.04 and Mint 20.2/20.1.

Your issue is likely down to the stock kernel installed by default, Linux Kernel 5.4. Newer hardware requires a newer version of the kernel for support. Kubuntu 21.04 installs a 5.11 kernel out of the box.

Open Update Manager - View - Linux Kernels - install a 5.8, 5.11 or 5.13 kernel. Reboot after install.

**Comment by AnimationPredictors** [comment]
I have firepro w4300 and in opencl usage scenarios the "cinnamon wrapper unexpectedly crashes" erorr pops up. 
Then some icons dissapears and screenshots not working. When turning off computer, giving the erorr Read only file system. I dont if its related or thats my hardware

 I had that issue for couple weeks on 20.2, too. But it worked on 20.2 all the time. Im using stock kernel, so maybe I should downgrade the stock kernel?

I tried the Kubuntu, which I didn't like. I downgraded stock kubuntu kernel to 5.4 and drivers seems to work despite system quirks itself

**Comment by xenopeek** [comment]
If a kernel newer than 5.4 is needed for this system, the Linux Mint Edge ISO is probably what you need: https://linuxmint-user-guide.readthedocs.io/en/latest/edge.html. Currently it comes with kernel 5.11. The Edge ISO will be upgraded to Linux Mint 20.3 after the beta and will then come with kernel 5.13 I think.

**Comment by MortenPiil** [comment]
Thanks, Xenopeek - the edge version works!
I think the fact that there is an edge version should be clearer on the homepage - I never knew it existed.
At least it could be mentioned in the readme.
But thank you - now I can get back to Mint after my Kubuntu exile - and I will just wait patiently to update to 20.3.
Morten
