### ISSUE TITLE
flatpak: upgrade to 1.12.2

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#18]
What is indicated in the ['New Features at Cinnamon'](https://www.linuxmint.com/rel_una_cinnamon_whatsnew.php) / [MATE](https://www.linuxmint.com/rel_una_mate_whatsnew.php) / [Xfce](https://www.linuxmint.com/rel_una_xfce_whatsnew.php) (Flatpak 1.12)  does not correspond to the installed [package](http://packages.linuxmint.com/list.php?release=una#backport) at Mint 20.3.

>mint@mint:~$ flatpak --version
Flatpak 1.11.2

**Comment by WhosyVox** [comment]
Indeed the shipped flatpak in the Una repositories does seem to be 1.11.2-1flatpak1~20.04

http://packages.linuxmint.com/list.php?release=una

**Comment by clefebvre** [comment]
Thanks guys, it's the other way around though, we want 1.12.2 in the repositories, the website is right. We'll get this backported.

**Comment by MikeNavy** [comment]
Hi,
Flatpak is a security application, it runs apps in a sandbox. As any security app, it should be updated on a regular basis, and not only occasionally when Mint releases a new version. The history of flatpak releases shows enhancements, bugs corrections, and security fixes. It is important to have the security fixes available as soon as they are released. Moreover, flatpak evolves rapidly, there are lots of issues (656 open on 25 December).  My suggest, add flatpak stable ppa: [https://launchpad.net/~flatpak/+archive/ubuntu/stable](https://launchpad.net/~flatpak/+archive/ubuntu/stable) to the list of repositories. This ppa is maintained by flatpak authors, and its sources are there: [https://github.com/flatpak/ppa-flatpak](https://github.com/flatpak/ppa-flatpak).
Regards,
MN
