### ISSUE TITLE
mintwelcome: Refs to obsolete mint-y-dark metacity theme

### ISSUE THREAD

**Issue by hugok79** [linuxmint/mint20.3-beta#19]
![Captura de ecrã de 2021-12-14 21-09-15](https://user-images.githubusercontent.com/16929048/146080625-d8492db5-4546-4682-be70-e939f0cda70e.png)
![Captura de ecrã de 2021-12-14 21-18-13](https://user-images.githubusercontent.com/16929048/146080832-6f0007a4-1d50-4b1c-8b2a-c41fe3ecfdba.png)

**Comment by haggen88** [comment]
I confirm this happens after switching to dark mode in 'mintwelcome'

**Comment by hugok79** [comment]
Yes, toggling dark mode on in the Mintwelcome app results in the Mint-Y window border preview displaying as a solid grey when opening the Themes menu.

**Comment by WhosyVox** [comment]
I mentioned this in passing on a previous bug report but neglected to open a report for it. Thank you for posting.

**Comment by clefebvre** [comment]
Fixed https://github.com/linuxmint/mintwelcome/commit/8544814a4bc1766536623319dc81f6725702cf62
