### ISSUE TITLE
mintwelcome: does not remember state of Light/Dark toggle

### ISSUE THREAD

**Issue by WhosyVox** [linuxmint/mint20.3-beta#2]
As the title implies, the Mintwelcome app does not appear to set the state of the Light/Dark theme toggle upon re-opening.

Steps to reproduce:
1. Open Mintwelcome
2. Set the theme to Dark under the 'First Steps' tab
3. Close the window
4. Re-open Mintwelcome and check the state of the toggle switch

Expected result:
The toggle should be set to Dark

Actual result:
The toggle is set to Light

Tested within a VM on the Mint 20.3 Cinnamon ISO, fresh install.
I expect this behaviour was not desired previously as themes were entirely separate for light/dark modes, but now this distinction is important as Mint themes are able to somehow infer their colours from this state.

**Comment by hammy275** [comment]
Related: I have [a PR open in mintwelcome's repository](https://github.com/linuxmint/mintwelcome/pull/50) that fixes this.

**Comment by haggen88** [comment]
reproduced
![toggle b](https://user-images.githubusercontent.com/68134588/145945294-7b213113-2fd3-4bfc-bd90-827428d1136b.png)

**Comment by clefebvre** [comment]
Fixed in 2.5.2, thanks @hammy3502 !
