### ISSUE TITLE
celluloid: missing translation of an option in the preferences menu

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#21]
![falta traducir linea](https://user-images.githubusercontent.com/68134588/146106089-7d7f8f8d-94a6-46fe-902b-93b2b9dd1ce3.png)

I couldn't find the line in the .po file in the [Mint fork](https://github.com/linuxmint/celluloid/blob/master/po/es.po)

But the line appears in the translations [updated about 2 months ago] in the celluloid-player [repository](https://github.com/celluloid-player/celluloid/blob/master/po/celluloid.pot):

#: data/io.github.celluloid_player.Celluloid.gschema.xml:78
msgid "Always append opened files to playlist"
msgstr "Always append opened files to playlist"

---

PS. The example is with the Spanish translation, but the missing line is not found in any .po translation file in the Mint fork. 
PS. Is it possible for Mint 20.3 to have Celluloid v0.22 ?
Btw The same missing line is present in Celulloid of Mint 20.2.

**Comment by hugok79** [comment]
Celluloid translations were made in Zanata but now are made in https://hosted.weblate.org/projects/celluloid/

**Comment by clefebvre** [comment]
0.22 depends on GTK4. Other than potential regressions this could cause, we don't have GTK4 in the 20.04 package base.

This looks like it's broken in 0.21 upstream basically.
