### ISSUE TITLE
thingy needs the description on its UX for support type of doc.

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mint20.3-beta#22]
The user does not know what type of document is supported.
If there is no description on the UX of the application, the user will expect that Libre office files are also supported. 
![スクリーンショット 2021-12-15 13-53-17](https://user-images.githubusercontent.com/78515193/146125697-39dd08f9-7922-48ab-b944-1cb5e3416a66.png)

**Comment by clefebvre** [comment]
It's a good point... although thingy will eventually support many different types of documents and have a filter to switch between between them.

**Comment by clefebvre** [comment]
This will be a wontfix for now. It'll sort itself out in the upcoming  versions.

**Comment by vegam57** [comment]
For example, I think it is necessary to describe that even if you add a favorite mark to an image file, it will not appear in Thingy.
At the time of the birth of this app.
That's what I wanted to say.
