### ISSUE TITLE
no boot on Apple MacMini2,1

### ISSUE THREAD

**Issue by PeterKamm** [linuxmint/mint20.3-beta#25]
LM20.3beta cinnamon does not boot on Apple MacMini2,1
tested from external DVD, USB-Stick and ventoy.net/USB-SSD

AMM2,1 has an EFI32 (can not be updated) but a Core2Duo (64Bit) and an internal Apple-DVD-"Superdrive". Usually AMM2,1 does not boot from anything else than Apple-DVDs or USB-Sticks / Drives with MOX and MOX-installers.

I know, this is a quite rare and schidzo scenario: EFI32 on a 64-bit-Intel-machine, internal broken "Super"-DVD-drive, several means by the manufacturer to prevent booting / installing "alien" OSes from USB-stick and -external-drives .... 
BUT
anyhow with a Debian-multiarch-CD on an external USB-DVD-drive and with ventoy on a external USB-SSD I could boot (by EFI32 and other means) and from the DVD I could install Debian 11. From ventoy/USB-SSD I could not boot further into any of the (on the ventoy-SSD) stored Linux-distis on the AMM2,1 (on other PCs, this works well).
Somehow D11-multiarch and ventoy did the trick to boot on an AMM2,1 and maybe LM could copy the trick, maybe at least for LMDE ... 

LM20.2 and LMDEV4 32/64 do boot boot either on AMM2,1 testet from ventoy and some of them tested by external USB-Stick or external DVD-drive. Only once I was able to boot LM19.3m32 from the internal Super-drive after several attempts (booting hangs sporadically because of DVD-read-problems), installed it and the installed LM19.3m32 did not boot on the AMM2,1 (the same LM19.3m32-DVD did not boot on the external USB-DVD-drive).

**Comment by WhosyVox** [comment]
Just to confirm, are you saying you are definitely able to get a Mint 20.2 ISO to boot but not any of the 20.3 ISOs?

**Comment by PeterKamm** [comment]
No, LM20.2 did not boot on AMM2,1.

Only with LM19.3m32 from the internal DVD-drive once after many trials, I was able to boot it, installed and the installation did not run. From a USB-Stick, external DVD-drive or ventoy/USB-SSD, it did not boot.

**Comment by WhosyVox** [comment]
I see. I wonder if this is due to Ubuntu 20.04 having dropped support for 32-bit systems. Support for 32-bit EFI may also have been dropped in that same update. If this is true, I don't think there's anything the Mint team can do to resolve the problem.

**Comment by PeterKamm** [comment]
Not supporting EFI32-boot seems to be the main issue, but not the only one. The next LMDE-32 could support booting and running the wired AMM2,1. Hopefully I will remember to post this issue into the LMDE5-32-beta discussion.
