### ISSUE TITLE
mint-themes: Artefacts on rounded corners

### ISSUE THREAD

**Issue by AwesamLinux** [linuxmint/mint20.3-beta#26]
![corner](https://user-images.githubusercontent.com/43387963/146275187-4aae84d1-f979-4473-8403-4327dda1827e.jpg)
(had to take photo with a camera, because problem disappears when taking a screenshot)

With the new rounded corners, black pixels on the edge of the corner intermittently appear (transparency issue I believe).

To replicate open up a few windows (on the example above I had three open), then click between the windows (to activate/bring them to front) and the problem may appear in one of the windows. 

(I only tried this in the USB live environment with the Mesa drivers it came with, GPU is a RX5700)

**Comment by SebastJava** [comment]
Also showing there: https://github.com/linuxmint/mint20.3-beta/issues/5#issuecomment-994879509

**Comment by ghost** [comment]
![pixels](https://user-images.githubusercontent.com/93754083/146307757-de9cade3-1f51-406c-a206-dac2749e7bc2.png)

Can confirm the bug on both the left and right ends of the title bar but when zooming the screenshot, the pixels appear reddish. Bug affects applications with rounded top corners as illustrated above in the screenshot like nemo, xviewer, xreader, mintstick, gimp, inkscape when light theme is used. Dialog boxes like User Authentication and Session dialog, and applications with less rounded corners are not affected like Mint Welcome, Thingy, gnome applications like Gnome Disks and Gnome Logs, and Gimagereader as illustrated below:

![dialog](https://user-images.githubusercontent.com/93754083/146309903-b5397a86-0cdd-4e11-905f-0dce479f74c9.png)

![less rounded](https://user-images.githubusercontent.com/93754083/146308351-1d5e2146-cbec-436d-bf3a-77418b9722bd.png)

**Comment by clefebvre** [comment]
We can't fix it just yet unfortunately. It's an issue with metacity and the antialiasing in muffin/cinnamon. It was already an issue before, it's just more visible when the radius is higher.

We're working on a mutter rebase (hopefully landing in cinnamon 5.4 / mint 21) and with that we'll switch all windows to Gtk rendering and abandon metacity themes. This will solve this problem.

**Comment by Harry-W-Haines-III** [comment]
Does this mean the end of official support for the Mint-X theme?  Or this applies just to Mint-Y?

**Comment by clefebvre** [comment]
Whether it's in Mint-Y, or Mint-X, or any theme... right now we're rendering titlebars in two different ways depending on the application:

- If the app has no headerbar (an SSD window in other words), we give it a titlebar using the metacity theme, and a shadow (which isn't themeable).
- If the app has a headerbar (a CSD window in other words), Gtk handles the headerbar and the shadow, and both are themed using  the Gtk theme.

What we're hoping to do in the future is simply to use the Gtk theme to render SSD titlebars and shadows. This would make all windows have the exact same shadows, and corners/buttons. Right now they kinda look the same if you don't look at them too closely. This is for every theme.

The impact on themes is simply the loss of metacity themes and the inability to set titlebars to a different theme than Gtk controls.

You can test this with metacity if you want. Ironically, by default, metacity actually doesn't use metacity themes. It renders everything with the Gtk theme.

**Comment by LinuxOnTheDesktop** [comment]
It is unfortunate that Mint is implementing rounded corners before a fix for a problem with rounded corners is available. I am sorry to party-poop, but perhaps the implementation of the rounded corners should have been delayed.

Given this problem, I for one will be installing the legacy themes package straightaway. Or at least I will if the bug affects dark themes. Note also that Mint is liable to receive multiple reports of the problem.
