### ISSUE TITLE
WLAN authentication not worked automatically

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint20.3-beta#27]
Mint 20.3 Cinnamon Beta in Live-System:

My WLAN could not be connected at first. In the **network connections**, "none" was selected under Security. In the **network settings**, it said "WPA3". The WLAN only worked after I switched to WPA2 under **network connections**. Shouldn't the appropriate option be selected automatically?
I never had this problem with the same hardware (just with a current Linux Mint 20.2). 
WPA3 is only offered in the **network connections** under security. In the **network settings** this option is not available at all, there is only WPA2. 

```
~$ inxi -nxz
Device-2: AVM FRITZ WLAN N v2 [RT5572/rt2870.bin] type: USB driver: rt2800usb bus ID: 1-3:3 
IF: wlx246511442b25 state: up mac: <filter> 
```

**Comment by clefebvre** [comment]
Hi Jakob,

I'd say it's either upstream or down to hardware/networking circumstances..  we didn't change anything in Cinnamon which could affect this between 20.2 and 20.3.

**Comment by jakoblm** [comment]
Ok thanks. However, it's strange why it happens. I use the same hardware and kernel in Mint 20.2.
