### ISSUE TITLE
mint-theme: Mint-Y Cinnamon thumbnail outdated

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint20.3-beta#28]
Mint 20.3 Cinnamon in Live-System:

In the theme settings, the preview images of the new "Mint-Y themes" for the desktop are not displayed correctly. The preview images show a dark panel, although the theme actually uses a light panel.

**Comment by SebastJava** [comment]
This could be done automatically with this: https://github.com/linuxmint/mint-themes/pull/308

But it requires an update, of course.

And then you could easily re-do it all once you finally get my "less professional" colours... :)
