### ISSUE TITLE
Settings for the dark mode in the X-apps difficult to find

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint20.3-beta#29]
Mint 20.3 Cinnamon in Live-System:

The settings for activating the dark mode in the X-apps are not consistent and therefore difficult to find. In Pix and in the Terminal this option is under "General", in Xviewer under "Modules".

**Comment by clefebvre** [comment]
This could be a feature request on Xviewer to integrate this option directly in the app as opposed to a plugin. It's not a bug per se for the scope of this BETA though.

**Comment by LinuxOnTheDesktop** [comment]
@jakoblm 

When you file the problem [here](https://github.com/linuxmint/cinnamon/issues). For, it is, indeed, a lack of usability. (My link is the Cinnamon tracker. Actually though I am unsure whether that is exactly the right place to file the issue.)

**Comment by jakoblm** [comment]
Ok I have opened a new issue here: https://github.com/linuxmint/cinnamon/issues/10539
