### ISSUE TITLE
"/usr/local/share/fonts/" has "staff" as group permission

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint20.3-beta#3]
For the:  linuxmint-20.3-cinnamon-64bit-beta.iso 

A rather minor detail that could be corrected before the SR ISO.
It was noticed that "ll" on "/usr/local/share/fonts" showed the following:
total 12
drwxrwsr-x 2 root staff 4096 Dec  9 07:45 ./
drwxr-xr-x 7 root root  4096 Dec  9 08:07 ../
-rw-r--r-- 1 root staff   36 Dec  9 07:46 .uuid

**Comment by clefebvre** [comment]
This is upstream from us: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1749204.html. It looks like it's like that in all Debian derivatives.
