### ISSUE TITLE
Individually customizable close button?

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint20.3-beta#30]
Mint 20.3 Cinnamon in Live-System:

The close button in Nemo is larger than the icons in the list view. This draws attention strongly to the upper right corner. It would be nice if I could determine the size of the buttons myself in the future

**Comment by clefebvre** [comment]
You mean the titlebar close button?

**Comment by jakoblm** [comment]
Yes, that's the one I mean.

**Comment by clefebvre** [comment]
This is up to the theme, I'm sorry this cannot be configurable by the user.
