### ISSUE TITLE
firefox: random crash

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#31]
I was watching stream on Twitch and had other tabs [Reddit,Github,Youtube,G.drive, etc]. And Firefox 95 closed unexpectedly. I have no memory or CPU consumption issues.

Apparently it's something regarding [WebRender](https://bugzilla.mozilla.org/show_bug.cgi?id=1741956), which they fixed in version [95.0.1](https://www.mozilla.org/en-US/firefox/95.0.1/releasenotes/)

**Comment by clefebvre** [comment]
95.0.1 is coming tomorrow.
