### ISSUE TITLE
Proposal to color the two corners  to Black when maximizing the window

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mint20.3-beta#32]
Proposal to color the two corners  to Black when maximizing the Firefox window
Is there another measure? 
![無題](https://user-images.githubusercontent.com/78515193/146496869-91030578-52e8-40fc-9ca8-21afdc60294c.png)

**Comment by clefebvre** [comment]
It's not up to us. This is a bug in FF. Our corners aren't rounded when maximized.

**Comment by LinuxOnTheDesktop** [comment]
I looked for a report of the Firefox bug, [here](https://bugzilla.mozilla.org/buglist.cgi?short_desc=corner&query_format=advanced&short_desc_type=allwordssubstr&product=Firefox&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&resolution=---&order=Importance), but I could not find one.
