### ISSUE TITLE
Possible mate-screensaver bug (now confirmed)

### ISSUE THREAD

**Issue by fblais** [linuxmint/mint20.3-beta#35]
Hi.
Running the 20.3 MATE beta here.
I'm not sure if that's a mate-screensaver bug, but here's what's happening:

I left the computer alone for a while.
When I come back, sometimes, instead of seeing the screensaver (epicycle), the display is dimmed,
Very dimmed, I almost don't see anything.
The sole way to stop that is to logout/login.
Sometimes the screensaver kicks in, other times, it's the display dimming.
The energy manager (gestionnaire d'énergie) is set to never put the computer or monitor in sleep mode.

Thanks!

**Comment by clefebvre** [comment]
hi @fblais,

I'm not sure what to say. I hope you find the cause of the issue. Ask people on the IRC or forums to help you troubleshoot. You're only at the observation phase though. If you find a bug, and especially if it's a regression in MATE 1.26 (or 20.3 in general), don't hesitate to reopen an issue here.

**Comment by fblais** [comment]
After I uninstalled mate-screensaver and installed Xscreensaver, the bug was gone.
So this confirms there's a bug in mate-screensaver, as far as I can tell.
