### ISSUE TITLE
Warpinator: Preferences menu button does not work in some network configurations

### ISSUE THREAD

**Issue by WhosyVox** [linuxmint/mint20.3-beta#36]
In the Warpinator build shipped in the Mint 20.3 beta, the 'Preferences' button does not open the Warpinator Preference window.
I've tested this bug in two separate beta VMs, and confirmed it works both within a 20.2 VM and a live Mint 20.2 system.

Sadly there is no stdout for this application that I can find, so I have been unable to track the cause of the bug.

**Comment by mtwebster** [comment]
There's no error message if you run 'warpinator' in a terminal? (Make sure it's not already running).

Does the button itself do nothing? Or clicking the preferences item?

**Comment by WhosyVox** [comment]
The button has no visible effect. You click it, the context menu closes and nothing appears to happen.
(I'm going through every Mint app in high DPI scale to check for any scaling or other issues.)

Curious, maybe a background process was the issue in getting terminal output.
See below a stack trace of the error, image due to working in a VM without copy/paste between host and guest.

https://i.imgur.com/P1IkCTr.png

Perhaps this issue is specific to VMs or unusual network setups? Though previous versions did not suffer from this problem.

Edit:
It looks like the application expects the output of the lshw call to have 'logicalname' as an attribute to the direct children of the array. That is, j[x].logicalname
In my case that attribute is only available on j[x].children[y].logicalname

In VM: https://i.imgur.com/ATC96M0.png
On host: https://i.imgur.com/Za9bQTJ.png

Given both are possible network layouts, should extra code be added to support this?

**Comment by mtwebster** [comment]
Weird I haven't seen that before. In 20.2 warpinator release we used network-manager to detect interfaces. I had to get rid of that because I couldn't package it as a flatpak and it wasn't available on all distributions/platforms.

Yes we can definitely update this to handle child nodes, I'm just interested in creating a test setup for it. What vm software are you using? I normally use vbox.

**Comment by WhosyVox** [comment]
I'm using QEMU/Libvirtd with the default network settings.

I wonder if file transfers will still work with this bug - that is, if it's purely an issue with fetching details for display or if it entirely blocks being able to use the app itself.

**Comment by mtwebster** [comment]
Does it connect if you run this:
```
gsettings set org.x.warpinator.preferences preferred-network-iface enp1s0
```
and start warpinator?

You can run `warpinator --debug` to get more debugging output (too much honestly).

**Comment by WhosyVox** [comment]
I think the reason it's failing to connect is due to subnet. The version on my host system (Mint 20.2) won't allow me to select the VM's network to connect to for some reason, so I can't get a working connection between host and guest.
e.g. The guest's on 192.168.122.x while the host's on 192.168.1.x

I only get enp0s31f6 as an option, despite having virbr0 and virbr0-nic as available networks. This is on an outdated version though - I'll try getting the Una copy on my system.
Edit: the copy in 20.3 actually does pick up on these networks so good job. Though it also says I'm not connected to a network? How's it determine this?


Without running the above the main window does already display enp1s0 in the bottom-right corner, with the correct IP address. So this bug may only be an issue for the preference menu.

**Comment by mtwebster** [comment]
I've improved/fixed a couple of things - if you'd like to try them:

Save these files:
https://raw.githubusercontent.com/linuxmint/warpinator/master/src/prefs.py
https://raw.githubusercontent.com/linuxmint/warpinator/master/src/networkmonitor.py

copy them both to /usr/libexec/warpinator
```
sudo cp *.py /usr/libexec/warpinator
```

This should take care of preferences not opening, as well as do a better job  connecting with available networks.

**Comment by mtwebster** [comment]
Closing this as the original issue should be fixed (prefs not opening)

Let me know when you get  a chance to test the changes (either via my instructions above or a new version  which should be coming in the next day or so).

**Comment by WhosyVox** [comment]
Ah apologies, Christmas and all.
While I could not get a stable connection (likely due to the configuration of the network through KVM), the menu was displaying properly with the above patches.

**Comment by mtwebster** [comment]
I set up a machine using virt-manager and qemu/kvm to test this, and could select the virtual interface on both host and guest and they connected without any issue (with the network interface showing as a 'child' node in lshw).

Did you update both the host and guest files?

I'll recheck when I get a chance to show my network info for the guest.

**Comment by WhosyVox** [comment]
I did not update the files on my host as I didn't want to faff about with my live system at the time, even with timeshift active.

I trust that if you've gotten it to work then it should, but I guess we'll see for sure once I do an upgrade to 20.3.
