### ISSUE TITLE
meta-issue: https://linuxmint-installation-guide.readthedocs.io/en/latest/verify.html (A newer and easier integrity check)

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint20.3-beta#37]
Are you expecting me to carefully compare this long checksum string? Using my own old brain ? That's too much trouble !

This https://linuxmint-installation-guide.readthedocs.io should give more modern and easy options:

```
cd Downloads
sha256sum -c --ignore-missing sha256sum.txt
```

**Comment by clefebvre** [comment]
https://gitlab.com/linuxmint/documentation/installation-guide/-/merge_requests/18
