### ISSUE TITLE
xfce: keyboard layout switching // using short-cuts

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/mint20.3-beta#38]
Setting up keyboard shortcuts to switch between additional keyboard layouts needs some looping to get it working at all - there seems to be some initial trigger missing to make the install aware of the 2 (or more) layouts.

This glitch existed with previous versions of mint xfce too ==  help/support case at irc - user running 20.2 xfce (on bare metal) but exists likely for some longer time (since 20.0 ?) - could be verified at a quem/kvm VM (identical setup as for the beta version) that time too.

Steps to reproduce - (see 5.1 for a potential workaround - starting point to debug)
+ screen-recording https://www.orcus.de/video/mint-20-3-beta-xfce-keyboard-shortcut-setup.pm4

(running at qemu/kvm vm with spice-vdagent installed - unmodified/restored to:)
Using mint 20.3 beta XFCE fully updated 
The initial install has been done using a german keyboard layout.

0. preparation - just for taking a screen-recording (not needed for an actual test)
0.1 apt install screenkey
0.2 add screenkey to startup-applications/session-startup
0.3 logout/login
0.4 tail -F ~/.xsession-errors  # to catch errors/messages as they show up

------------------------------------

1. using keyboard settings tool
1.1 add an en-US keyboard layout
1.2 define short-cut  - both ctrl-keys (has to be used: left ctrl 1st + right ctrl 2nd)
Note: The actual short-cut could be some different key-combo too and isn't seemingly the reason.
1.3 close keyboard settings tool

2. pressing lef-ctrl + right-ctrl doesn't switch keyboard layout

3. logout/login (test if this would trigger some property refresh) didn't help

4. add keyboard layouts plugin (this might not be required - but helps at least to pinpoint when things start working) - esing the plugin:
4.1 observation
Does not switch to 2nd layout using a left mouse click onto the panel plugin, which is the default behavior as long there are only 2 layouts defined // with more than 2 layouts the plugin would show a list/menu of available layouts/countries first, to pick one => keyboard layouts plugin can't "see" for some reason available layouts too.

4.2 using right-click keyboard layouts plugin -> keyboard settigs -> section layouts - resorting keyboard layouts / adding / removing layouts this way doesn't trigger anything too.

4.3 logout/login and retest shows not effect

5. run keyboard settings tool -> section layouts
5.1 turn  ON and OFF "Use system defaults" option once without closing the dialog does seemingly trigger some needed refresh.
5.2 close settings dialog
5.3 left-click onto keyboard layouts plugin - should start switching layouts
5.4 (after?) being able to switch layouts using the mouse .. the short-cuts start working as expected

6.remove keyboard layout pluging tool
6.1 logout/login
6.2 keyboard shortcuts are still working

**Comment by clefebvre** [comment]
Found upstream https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/310
Fixed in 4.16.2, backported to 20.3.

**Comment by orcus-de** [comment]
nice finding - perfect, has been annoying for xfce users in the past
cheers orcus
