### ISSUE TITLE
Nemo doesn't show file conflict dialog on Move to, only on Copy to

### ISSUE THREAD

**Issue by proulxf012** [linuxmint/mint20.3-beta#40]
While trying to update a theme file, I right clicked on the new file (in superuser mode) and clicked on "move to" then "go to" or "browse" and the to the file I want to update. Usually Nemo asks what we want to do then but all it does is save the new file beside the old one with "copy" in brackets. To update my file I had to remove it and save the new one in it's place.
Does this every time. Even in normal mode.

**Comment by proulxf012** [comment]
This seems to be happening in superuser mode. As a regular user (while updating my files back-ups) everything worked as advertised. This odd behavior happened again when I tried to update a few icons files in /usr/share/icons in superuser mode.

**Comment by proulxf012** [comment]
More info: everything works as is supposed to when "copy to" is used as opposed to "move to". This is new. Up to LM 20.2, I always used "move to". Looks like I will have to use "copy to" from now on.

**Comment by xenopeek** [comment]
I don't know if this is a bug or intended behavior. To summarize the issue:

- The file conflict dialog is shown on Linux Mint 20.2 for Copy to _and_ for Move to if a file with same name already exists at the destination. Of Linux Mint 20.3 beta it is _only_ shown for Copy to.
- On Linux Mint 20.3 beta when for Move to a file with the same name already exists at the destination it instead **changes the name of the file being moved to "filename (copy)".** Doesn't show the file conflict dialog to let the user decide how to handle the conflict.

The behavior is the same for regular user and root user.

The file conflict dialog on Linux Mint 20.3 beta for Copy to when a file with the same name already exists at the destination:
![image](https://user-images.githubusercontent.com/21159972/146671768-5d70d7e2-80fe-4a86-8286-9fc5ef69906b.png)

The same should probably be shown for Move to.

**Comment by Shawnecy** [comment]
Confirmed that I get this issue when I try to move using any method (move to, ctrl-x + ctrl-v, or click and drag).

Perhaps the most annoying part of it is that undo just undoes the move, not any renaming it did.

**Comment by mtwebster** [comment]
Fixed: https://github.com/linuxmint/nemo/commit/78f2e09be9ce24d52cfb0c9ba1971826e5ea85fa
