### ISSUE TITLE
Live session: Don't lock me out during testings or installation, please !

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint20.3-beta#41]
```
LinuxMint Cinnamon 20.3-beta
```

![Screensaver-live](https://user-images.githubusercontent.com/31940713/146617307-2c2048e5-2861-458f-81b9-0180f22c7b0d.png)

These are the default settings on a live session. It seems I could get locked out during testings and/or installation ? I guess it would be better with these default options:
* Never
* Off
* Off

**Comment by clefebvre** [comment]
Does it actually lock you out? I've got the feeling it either doesn't lock, or does so without needing a password.

**Comment by SebastJava** [comment]
@clefebvre Okay, sorry, there is no problem here. This is just an old nightmare from Mint Mate 18.x.

Now, I tested this from a LIVE session, with no custom settings except the delay was changed to 1 minute to quickly test this and... all you have to do is touch the mouse or the keyboard. I know the username is "mint" and the password is [nothing], but still, this could be frightening, when you don't know this.

But **on this 20.3 Cinnamon**, really, all you have to do is to touch something. Anything. So, there is no problem there.
