### ISSUE TITLE
mintsources: "Failed to download repository information (cdrom)" error in live mode

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint20.3-beta#42]
`LinuxMint Cinnamon 20.3-beta`

![Failed-to-download-repository-info](https://user-images.githubusercontent.com/31940713/146618828-1af25241-b364-43fd-8c78-85447ba44e83.png)

I am on VirtualBox. I am running a LIVE session using a virtual CD: the 20.3-cinnamon-beta disk file chosen from the Storage Settings.

**Steps to reproduce:**
1. Go to Software Sources.
2. Change some mirrors.
3. When prompted, click OK to update the APT cache.
I get the error message displayed in the screenshot above.

**Comment by SebastJava** [comment]
No error message after doing a complete install. :)

**Comment by WhosyVox** [comment]
It seems this isn't a new issue, the results are identical (albeit a different cd name) on Mint 20.2.

**Comment by LinuxOnTheDesktop** [comment]
> It seems this isn't a new issue, the results are identical (albeit a different cd name) on Mint 20.2.

This little wart has existed for years.

**Comment by SebastJava** [comment]
> That's not to say we shouldn't fix other issues.

This is written in the README file. Being an old issue is not a good reason to avoid it. Quite the opposite, IMHO. It may not be critical, but this strange error message appears right at the entry door: the live session. That does not make a good first impression.

**Comment by LinuxOnTheDesktop** [comment]
@SebastJava 

Indeed; the older the wart, the uglier.

**Comment by WhosyVox** [comment]
Indeed it should absolutely get fixed, but it probably won't be considered a beta-blocker. Get it fixed in time for the 21.0 release for sure though, it is definitely something that would unnerve users to see.

**Comment by SebastJava** [comment]
Same bug on a LIVE USB flash drive. (No virtual machine.)

**Comment by clefebvre** [comment]
Postponed towards Mint 21. We're likely to work on ubiquity and the APT backends for the next release.
