### ISSUE TITLE
Don't let me shut down without warning me about unsaved documents !

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint20.3-beta#44]
```
VirtualBox installed LinuxMint Cinnamon 20.3-beta
Cinnamon version 5.2.6
```

**Steps to reproduce:**
1. Create a second user account.
2. In your first user account, open Xed and write "Test". Don't save.
3. Open Menu > Logout: Switch user: to your second user account.
4. Shutdown from this second user account.

The computer shuts down immediately without warning you about this unsaved document in your first user account !

**Comment by clefebvre** [comment]
hmm... the fact that it doesn't know a document is not saved, I'm tempted to say that's normal. It's not the 2nd user's business to know that.

The fact that a user can shutdown the computer when other sessions are active, that's probably not OK... but then again, we're a desktop distribution, so one of the basic assumption here is that users have access to the hardware. If a user can indeed press the power button, then why stop him at software level... 

Either way, this is not a regression or a BETA bug. There's room for discussion here, probably upstream in lightdm or systemd/logind, but I'll close this here in the scope of the BETA.
