### ISSUE TITLE
lightdm: text error in the warning message

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint20.3-beta#45]
```
VirtualBox installed LinuxMint Cinnamon 20.3-beta
Cinnamon version 5.2.6
```

![Shutdown-warning](https://user-images.githubusercontent.com/31940713/146634533-dadeeb31-dbdc-4754-a56c-3ac18a11d10c.png)

"Copy text" ? What is this ?

**Steps to reproduce:**
1. Create a second user account.
2. Open Menu > Logout: Switch user.
3. From this lightdm login window, click in the top-right corner to Quit. (While you are still logged into your first user account.)

That's not a big bug. I appreciate this warning message, but it seems there is this typographic mistake: "Copy text".

**Comment by clefebvre** [comment]
aha, that's a funny one :)

I'll look into it, it should be easy to fix :)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/slick-greeter/commit/ab5a7ae49282e274c26cb2faf4814e29ca19b772
