### ISSUE TITLE
cinnamon: sound applet does not display the artwork when playing with celluloid

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#46]
As the title says. Rhythmbox among other players that I tested show the cover art in the sound applet, but Celluloid despite being installed in Mint by default does not integrate it.

![artwork](https://user-images.githubusercontent.com/68134588/146644429-198d19cd-388e-4c36-ad20-9bafecdee189.png)

**Comment by mtwebster** [comment]
This is not currently supported by celluloid.

It appears to only provide basic textual info to the applet:
https://github.com/celluloid-player/celluloid/blob/master/src/mpris/celluloid-mpris-player.c#L342-L349
