### ISSUE TITLE
firefox: Migrate to Mozilla configuration

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint20.3-beta#47]
- [x] Update Firefox to 95.0.1+linuxmint3
- [x] Update ubuntu-system-adjustments
- [x] Update live repositories

In preparation for a new partnership between Mozilla and Linux Mint, we're updating the Firefox configuration to the one used upstream. This is done here in this BETA first, so we can identify any regressions, before it gets rolled out towards stable Mint releases.

**Comment by WhosyVox** [comment]
Could you let us know (roughly) what kind of changes are being made in this regard? It would not only be interesting but possibly useful if bug hunting.

**Comment by Harry-W-Haines-III** [comment]
Well the first thing I noticed on Settings | General is the message on top:
![Screenshot from 2021-12-18 15-36-49](https://user-images.githubusercontent.com/45599505/146654897-0f452f89-b2e3-4b2b-81f4-2223e6012b70.png)

![Screenshot from 2021-12-18 15-38-02](https://user-images.githubusercontent.com/45599505/146654918-1a73acbb-94b5-4b1a-97a6-5fea09d1d45a.png)

I checked on the other computer running 59.0 and Linux Mint 20.2 Cinnamon Ed. and did not see this.
Usually I would see a message like this in a corporate environment.

**Comment by Tibladar** [comment]
`/usr/share/ubuntu-system-adjustments/firefox/distribution.ini` are where the policies come from:

```
# Partner Distribution Configuration File
# Author: Mozilla
# Date: 2016-10-05

[Global]
id=mint-001
version=1.0
about=Mozilla Firefox for Linux Mint

[Preferences]
app.distributor.channel="una"
app.distributor="mint"
app.partner.mint="mint"
app.update.enabled=false
browser.shell.checkDefaultBrowser=false
intl.locale.requested=""
mozilla.partner.id="mint"
widget.content.gtk-theme-override="#"
browser.backspace_action=0
```

**Comment by clefebvre** [comment]
> Could you let us know (roughly) what kind of changes are being made in this regard? It would not only be interesting but possibly useful if bug hunting.

It should be almost identical to the version available directly from Mozilla.

@Harry-W-Haines-III this is done so Firefox delegates updates to the OS via policy. The version you had before achieved this via code changes. We're planning to work with Mozilla in 2022 to improve updates and let people discover FF updates and apply them straight from within the browser. But for now, that's the expected behavior.

**Comment by ghost** [comment]
Since Google search engine will be installed by default, I think it is a good move for the end users.

I have a problem though. I'm getting frame drops on YouTube playback, especially on 60 fps videos. You can view the frame drop counts by right clicking on the video and selecting "Stats for nerds" option. Previous build was rock solid, so it's a regression.

**Comment by enigma131** [comment]
On my side i uninstall always Firefox and install in place Firefox esr. Less updates

**Comment by vegam57** [comment]
Pepper ducks appear in search engines
![スクリーンショット 2021-12-20 06-06-34](https://user-images.githubusercontent.com/78515193/146691019-9d538515-554d-4150-8ae7-d2b43f18bc64.png)

**Comment by clefebvre** [comment]
is that only in Webapps @vegam57 ? I wonder if it's part of a profile coming from ICE.

**Comment by vegam57** [comment]
> is that only in Webapps @vegam57 ? I wonder if it's part of a profile coming from ICE.

Yes,it is only Webapps profile.

**Comment by haggen88** [comment]
The new Firefox 95.01 in addition to the elements that @vegam57  points out, has another drawback. It has changed the search engine that I had already configured prior to the update. At first I didn't think anything of it and assumed it was part of the update, but it has changed my search engine 4 times today.

**Comment by Harry-W-Haines-III** [comment]
I had a custom script that prevented search engines from being changed every time Firefox was updated.  There were no changes in the default search engine from the jump 95.0 to 95.0.1 now that a slightly different method of passing the partner distribution information is being used (hence the script is no longer effective).  Amazon, Bing and eBay now appear in the Search Shortcuts list which had not in the past.  Assuming these came from Firefox?

Edit: **My mistake.   Amazon, Bing and eBay now appear in the Search Shortcuts list which had not in the past. <-- those were there before.  Put the system back the way it was on this computer before installing the Beta and discovered this.**  Each computer is slightly different in what search engines were inherited.

Hopefully, going forward, the user's previously selected default search engine setting will be respected on Firefox updates.  Or maybe now, Firefox will be doing that directly?

**Comment by clefebvre** [comment]
> The new Firefox 95.01 in addition to the elements that @vegam57 points out, has another drawback. It has changed the search engine that I had already configured prior to the update. At first I didn't think anything of it and assumed it was part of the update, but it has changed my search engine 4 times today.

Please explain in details what you had before, what you have now and what you expected to see.

@Harry-W-Haines-III it now ships with Mozilla's engines. User configuration was always meant to be preserved, in either versions. There have been changes throughout the years in the implementation both upstream and in Mint which might have affected that though. Note also that default isn't necessarily set in stone. If the default is changed by the user then it becomes user configuration, but if it's not, and the default value itself changes, then it changes for the user as well. It's similar to how gsettings works.

**Comment by haggen88** [comment]
>Please explain in details what you had before, what you have now and what you expected to see.

In Firefox 95 I had Google as my search engine. After the update it appeared with Yahoo! I reconfigured it and from time to time after closing the browser, Firefox 95.0.1 appeared with Yahoo! as the default search engine, deleting Google.

My 'home page' as well as the 'new tabs' are set to 'Firefox home' [default]. I do not have any Yahoo! plugins.
The add-ons I use are: uBlock,HTTPS Everywhere,Privacy Badger and To Google Translate.

I simply waited for Firefox to save the settings.

PS. Now I modified about:config parameters that were related to Yahoo. specifically:
>browser.search.param.yahoo-fr
>browser.search.selectedEngine

**Comment by clefebvre** [comment]
Can you paste the ouput of:

`apt policy firefox`

and

`apt policy ubuntu-system-adjustments`

**Comment by Zhoardkell** [comment]
For me google was completely removed when updating to 95.0.1+linuxmint1+una and yahoo added back to the list and set as default didn't happen again so far after adding google back.

```
:~$ apt policy firefox
firefox:
  Installed: 95.0.1+linuxmint1+una
  Candidate: 95.0.1+linuxmint1+una
  Version table:
 *** 95.0.1+linuxmint1+una 700
        700 http://packages.linuxmint.com uma/upstream amd64 Packages
        100 /var/lib/dpkg/status
     95.0+build1-0ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     75.0+build3-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```
```
:~$ apt policy ubuntu-system-adjustments
ubuntu-system-adjustments:
  Installed: 2021.07.08
  Candidate: 2021.07.08
  Version table:
 *** 2021.07.08 500
        500 http://packages.linuxmint.com uma/main amd64 Packages
        500 http://packages.linuxmint.com uma/main i386 Packages
        100 /var/lib/dpkg/status

```
```
:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma
```

Addons: uBlock Origin, Umatrix, IPvFoo

**Comment by haggen88** [comment]
@clefebvre  This problem happened to me in Mint 20.2 persistently. In Mint 20.3 it happened only a couple of times. After modifying the 'about:config' settings, it didn't happen again. 
[**update**: it happened again in Mint 20.2!]

Mint 20.3 output terminal
>mint@mint:~$ apt policy firefox
firefox:
  Installed: 95.0.1+linuxmint3+una
  Candidate: 95.0.1+linuxmint3+una
  Version table:
 *** 95.0.1+linuxmint3+una 700
        700 https://mint.zero.com.ar/mintpackages una/upstream amd64 Packages
        100 /var/lib/dpkg/status
     95.0+build1-0ubuntu0.20.04.1 500
        500 http://mirror.uchile.cl/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     75.0+build3-0ubuntu1 500
        500 http://mirror.uchile.cl/ubuntu focal/main amd64 Packages

>mint@mint:~$ apt policy ubuntu-system-adjustments
ubuntu-system-adjustments:
  Installed: 2021.12.17-una
  Candidate: 2021.12.17-una
  Version table:
 *** 2021.12.17-una 500
        500 https://mint.zero.com.ar/mintpackages una/main amd64 Packages
        500 https://mint.zero.com.ar/mintpackages una/main i386 Packages
        100 /var/lib/dpkg/status

---

Mint 20.2 output terminal

>h2gn@h2gn:~$ apt policy firefox
firefox:
  Instalados: 95.0.1+linuxmint1+una
  Candidato:  95.0.1+linuxmint1+una
  Tabla de versión:
 *** 95.0.1+linuxmint1+una 700
        700 https://mirror1.cl.netactuate.com/linuxmint/packages uma/upstream amd64 Packages
        100 /var/lib/dpkg/status
     95.0+build1-0ubuntu0.20.04.1 500
        500 http://mirror.uchile.cl/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     75.0+build3-0ubuntu1 500
        500 http://mirror.uchile.cl/ubuntu focal/main amd64 Packages

>h2gn@h2gn:~$ apt policy ubuntu-system-adjustments
ubuntu-system-adjustments:
  Instalados: 2021.07.08
  Candidato:  2021.07.08
  Tabla de versión:
 *** 2021.07.08 500
        500 https://mirror1.cl.netactuate.com/linuxmint/packages uma/main amd64 Packages
        500 https://mirror1.cl.netactuate.com/linuxmint/packages uma/main i386 Packages
        100 /var/lib/dpkg/status

---

 **PS**. It would be useful to enable the option to restore passwords from a csv file and make it easier to restore previous settings such as migrating other browsers to Firefox.  [hamburger button / Passwords  / ... menu > add option to 'import password from a file']

**Just change 'signon.management.page.fileImport.enabled' from 'false' to 'true'**.

**Comment by clefebvre** [comment]
95.0.1 changed the way the engines are refreshed. This was done to fix an issue in the migration to Mozilla's configuration. I believe 20.03 (which now ships with the mozilla config) is OK.

It looks like this causes a regression in stable releases though where the migration isn't applied yet.

**Comment by haggen88** [comment]
I uninstalled and purged firefox [plus did a cleanup with BleachBit], then installed Firefox 95.0.1 but the problem persists in Mint 20.2. [On Reddit there are already people reporting that problem]

Maybe these settings are related:

>extensions.reset_default_search.runonce.3 : true
>extensions.reset_default_search.runonce.reason: previousRun

**Comment by Zhoardkell** [comment]
Not sure whats going on but happened twice to me today.
But now after not touching my browser for few hours suddenly google is back and set to default but i also have Bing, Amazon.com and Ebay added to my search shortcuts.
Closed my browser reopened and now google is gone again and yahoo is back this getting annoying.

**Comment by Harry-W-Haines-III** [comment]
@Zhoardkell Very interesting observation!  Could it be synchronizing from another computer with the same account?  That is what happened to me.

**Comment by Zhoardkell** [comment]
> @Zhoardkell Very interesting observation! Could it be synchronizing from another computer with the same account? That is what happened to me.

No i don,t use that functionality.
Don,t use sync last time i touched my browser earlier this evening just had yahoo and duckduckgo browser was open few hours later i have google, duckduckgo, Bing, Amazon.com and Ebay no updates done nothing.

**Comment by clefebvre** [comment]
@Zhoardkell can you do the following?

- Close Firefox
- Reopen Firefox and verify that you have Yahoo as default, that the DuckDuckGo result URL contains t=lm and that the new engine page is from Linux Mint.
- Open up the console with Ctrl+Shift+J and leave it open on the side.
- Use Firefox or wait until it brings Google/Bing/Amazon back.
- Do a search with Google and paste the URL you get here.
- Do a search with DuckDuckGo and paste the URL here.
- Paste the content of the console (Ctrl+A, Ctrl+C to copy it all and pastebin it).

**Comment by clefebvre** [comment]
ah hold on, we're able to reproduce the issue.

**Comment by Zhoardkell** [comment]
@clefebvre I have been deleting everything related to yahoo and other things i don't use from .search in about:config it's not happening for me right now.

**Comment by clefebvre** [comment]
Quick update on this. Sorry it's taking a little while. It's extremely hard to reproduce.

Looking at the code though we've got a fair idea of where the regression is. We're preparing a fix.

**Comment by clefebvre** [comment]
We believe the issue is fixed in firefox 95.0.1+linuxmint1.1.

**Comment by clefebvre** [comment]
@vegam57 I confirmed the presence of the peppermint engine in webapp-manager. When we started this project, although it was written from scratch, it was inspired and made compatible with ICE (from the Peppermint project). The Mozilla profile it uses to create webapps is the same that ICE used. This was copied over including the search.json.mozlz4. It's not new in this BETA, it's been like that since the very start of the webapp-manager project. We'll update this probably after we migrate Mint to Mozilla's configuration. I made a trello entry for it in the roadmap.

**Comment by chptr-one** [comment]
> We believe the issue is fixed in firefox 95.0.1+linuxmint1.1.

My problem with reset the search engine completely disappeared after last patch. Thank you.

**Comment by vegam57** [comment]
> @vegam57 I confirmed the presence of the peppermint engine in webapp-manager. When we started this project, although it was written from scratch, it was inspired and made compatible with ICE (from the Peppermint project). The Mozilla profile it uses to create webapps is the same that ICE used. This was copied over including the search.json.mozlz4. It's not new in this BETA, it's been like that since the very start of the webapp-manager project. We'll update this probably after we migrate Mint to Mozilla's configuration. I made a trello entry for it in the roadmap.

Yes, I understand.
Thank you for investigating .

**Comment by Zhoardkell** [comment]
Since updating yesterday to 95.0.1+linuxmint1.1+una search engines haven't changed anymore.

**Comment by haggen88** [comment]
I also confirm that the update solved the problem. Thank you.

**Comment by clefebvre** [comment]
Thanks, no problem at all.

**Comment by vegam57** [comment]
If you don't have to worry, please skip this comment

Until 95.0.0, if the user-agent had "Ubuntu", I thought it would be Mint.
I noticed that "Ubuntu" is excluded in 95.0.1.
It may be a new fact if someone who manages the Firefox user-agent is included. 

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/95.0
↓
Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by dmitryvakulenko** [comment]
I sill have no google engine on My Linux Mint 20.2 Cinnamon and Firefox 95.0.1+linuxmint1.1+una. It appeared after firefox was updated, but missed after first reboot.

**Comment by aerkiaga** [comment]
Interesting... Could fix [this FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1699847), as I can only reproduce it on Mint right now. Maybe I'll test it again with the new configuration.

**Comment by haggen88** [comment]
@dmitryvakulenko  have you seen if when applying 'Restore Default Search Engines' they reappear?

The only thing I noticed is that with the latest update in LM 20.3 [LiveUSB], Bing and Amazon search engines now [appear](https://user-images.githubusercontent.com/68134588/147773977-a90723f7-ae79-4a6f-ac71-e887a1f77f44.png) [part of the Mozilla configuration I guess].


...

@aerkiaga I had no problems with that website on Mint 20.2/20.3 with Firefox 95.0.1+linuxmint1.1+una

**Comment by dmitryvakulenko** [comment]
@haggen88 
> have you seen if when applying 'Restore Default Search Engines' they reappear?

This button is disabled, I can't click it.

**Comment by clefebvre** [comment]
@dmitryvakulenko try with a new profile.

**Comment by clefebvre** [comment]
Live repo updated.
I can't reproduce the FPS issue. I get a few lost frames incidentally here and there, but I did with the Mint version also.

**Comment by dmitryvakulenko** [comment]
@clefebvre new profile didn't help. But I can add google search engine through Mint search engines page https://www.linuxmint.com/searchengines.php
