### ISSUE TITLE
cinnamon: inconsistency of accent on desktop elements

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#48]
Elements such as the 'lighting' of the icon in the taskbar, the sound and brightness applet controls, the accentuation of menu items or networks; show a different color than the one selected for the 'controls' which can be distracting.

![ac1](https://user-images.githubusercontent.com/68134588/146649869-220fb86e-0eda-4289-947a-def9ba2e98d6.png)

![ac2](https://user-images.githubusercontent.com/68134588/146649872-b1bdb40c-250c-482a-b3fb-1cfcff89a6bf.png)

Regards

**Comment by SebastJava** [comment]
@haggen88 I'm not sure I understand your arguments, but it seems you are confusing the Controls theme with the Desktop theme. Try setting both Controls and Desktop to the same colour ?

![Controls-Desktop-themes](https://user-images.githubusercontent.com/31940713/146652811-72870451-7a34-4a34-a589-94d45b1b6020.png)

**Comment by haggen88** [comment]
@SebastJavaif Yes was a confusion on my part.  I thought it was automatically linked.
