### ISSUE TITLE
Firefox - residual Title Bar when Title Bar is turned off.

### ISSUE THREAD

**Issue by Ethanol6** [linuxmint/mint20.3-beta#49]
Cinnamon 5.2.6
muffin 5.2.0

When Title Bar is turned off in Firefox, there are still 2-3 pixels of the Title Bar visible above the Firefox window. The corner radius is even visible, which looks weird behind Firefox's square corners.

## Steps to reproduce
Right click an empty area in Firefox's tab area and click "Customize Toolbar".
At the bottom of the page un-check the "Title Bar" box.

Could this be related to #32 ?

[https://github.com/Ethanol6/mintBetaTesting/raw/main/FFTitleBar.png](https://github.com/Ethanol6/mintBetaTesting/raw/main/FFTitleBar.png)

[https://github.com/Ethanol6/mintBetaTesting/raw/main/FFTitleBar2.png](https://github.com/Ethanol6/mintBetaTesting/raw/main/FFTitleBar2.png)

This is what it looks like with the Legacy Mint-Y-Dark theme enabled.
[https://github.com/Ethanol6/mintBetaTesting/raw/main/FFTitleBarLegacy.png](https://github.com/Ethanol6/mintBetaTesting/raw/main/FFTitleBarLegacy.png)

**Comment by mtwebster** [comment]
duplicate: https://github.com/linuxmint/mint20.3-beta/issues/5
