### ISSUE TITLE
New theme is broken on Firefox with CSD

### ISSUE THREAD

**Issue by Uldreth** [linuxmint/mint20.3-beta#5]
Description: When client-side decorations are used in Firefox, the rounded corners exhibit a visual glitch, the window buttons do not precisely follow the theme and the close button's outline is clipped.

Steps to reproduce:

1. Open Firefox
2. Right click on the tab bar and select "Customize Toolbar".
3. In the screen uncheck "Title Bar" at the lower left corner.
4. Observe the visual glitch.

Expected behaviour: The Firefox headerbar should have properly rounded corners and matching window buttons with the rest of the applications
![firefox_lm_theme](https://user-images.githubusercontent.com/29836149/145652031-f6963f2d-892d-429e-80f8-b8571ee68227.png)
.

**Comment by Uldreth** [comment]
![firefox_lm_2](https://user-images.githubusercontent.com/29836149/145652123-cd0765ab-ff86-48fc-ad67-86c87c316fd2.png)

**Comment by haggen88** [comment]
I confirm the bug [LM Cinnamon]. Firefox without Title bar cut the close button:

![firefox wo titlebar](https://user-images.githubusercontent.com/68134588/145696535-bd221ae7-2310-4676-ad37-8aa501760ae3.png)

**Comment by davidelng** [comment]
Just installed on a VM (haven't tested on an actual pc yet) and can confirm this.
![no-titlebar-firefox-dark](https://user-images.githubusercontent.com/83471198/145722827-81e39db6-4846-4040-a7cd-0be0aa77d273.png)
![no-titlebar-firefox-light](https://user-images.githubusercontent.com/83471198/145722832-22133226-e495-45da-8cb7-e20752e30870.png)

**Comment by Robb1010** [comment]
Can confirm as well

![Screenshot from 2021-12-14 22-17-52](https://user-images.githubusercontent.com/11844042/146088326-f8d8022f-8a68-413d-b1cb-fce27d4635b2.png)

**Comment by elduglas** [comment]
Nemo ![image](https://user-images.githubusercontent.com/9750729/146210884-a36d7ef1-858d-40b5-a206-6b62c0daaf98.png)

**Comment by mtwebster** [comment]
This is an issue in firefox that I need to submit a patch for. If you must have client decorations, run:
```
GTK_CSD=1 firefox
```
If you want to put this in a launcher, you'll need to wrap it in `sh`:
```
sh -c "GTK_CSD=1 firefox"
```
Note this will reveal an additional issue with enlarged X button:
![image](https://user-images.githubusercontent.com/262776/146217193-4d2fea12-ef37-4751-a0f1-096d7d86ff03.png)

**Comment by Jocadbz** [comment]
Can confirm. Used to work with old mint theme.

![bug](https://user-images.githubusercontent.com/83680590/146282072-f896e6c2-c876-4d80-ab0e-e2bc02865fc4.png)

**Comment by clefebvre** [comment]
Closing as upstream, we'll submit a patch to Mozilla.

**Comment by mtwebster** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1746486
https://github.com/linuxmint/mint-themes/commit/08ac147633d436c92d412e27d3ea375f1347dfe8
