### ISSUE TITLE
Themes: Window close button colour does not always match Controls colour

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint20.3-beta#50]
```
VirtualBox installed LinuxMint Cinnamon 20.3-beta
Cinnamon version 5.2.6
```

![Themes-windowborders-controls](https://user-images.githubusercontent.com/31940713/146653645-391f18d1-7e23-4705-b73d-85ae19c0eee3.png)

**Issue:** Window close button colour (Metacity only) does not immediately match Controls colour when changing those Controls colour.

**Steps to reproduce:** Just keep the default settings and change the Controls colour from some Mint-Y-LIGHT-COLOUR to some other Mint-Y-LIGHT-COLOUR.

Yes, I know, this is an old bug. I already told you this a long time ago. But now you have a new "dynamic" window border which changes automatically when switching the controls from light to dark or vice-versa. Great ! So, I was hoping this would fix this issue, but it did not. Well, if you also switch from light to dark, or dark to light, then it all works fine. Example: you can change Controls from Mint-Y to Mint-Y-Dark-Aqua and then it all works perfectly. But it doesn't work when changing the Controls from Mint-Y to Mint-Y-Aqua, as pictured above.

I guess we'll just have to wait for the GTK window borders...

**Comment by clefebvre** [comment]
We had a workaround for it but it consisted in tinted greys... feedback told us people weren't mad about that so we didn't do it.

When the base color is different this works fine. When it's the same, it doesn't trigger the change.

It's a silly bug.. and as you said it will go away when we move to Gtk borders. For now another way to force it to change is to switch the icon theme.
