### ISSUE TITLE
ubiquity: asks to unmount itself before disk selection

### ISSUE THREAD

**Issue by Ethanol6** [linuxmint/mint20.3-beta#51]
Linux Mint 20.3 Beta Cinnamon

## Observation
The installer asks the user if they want to unmount mounted partitions prior to the disk selection step. This occurs even if the only mounted partition belongs to the drive the installer is on and asks if the user wants to automatically unmount it. 

Clicking yes or no makes no difference, the installation proceeds normally.

## Expected Behaviour
The installer should recognize that it can't unmount itself and skip the step of asking the user to unmount partitions if the installer is the only mounted partition.

**Comment by mtwebster** [comment]
What installation media are you using here? A usb stick?

**Comment by Ethanol6** [comment]
> What installation media are you using here? A usb stick?

Yes, USB stick

**Comment by clefebvre** [comment]
This is a niche case. It doesn't normally happen. It's also upstream from us and not a new bug in ubiquity. I'll close this since it won't get fixed in this BETA.
