### ISSUE TITLE
[improvement] Reduce contrast between Panel and Window title bar

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/mint20.3-beta#52]
```
VirtualBox installed LinuxMint Cinnamon 20.3-beta
Cinnamon version 5.2.6
```
IMHO, the updated Mint-Y theme looks fantastic, but i think panel's colour should be updated as well, in order to reduce the contrast between panel and window title bar colours.

I use the panel at the top with dark mint-y theme and in the current state of Mint the panel along the window title bar looks very nice, like a big header, and it doesn't distract me. I can discern where everything is, including the separation of panel and window, and it feels like one consistent system. 

However, in the updated version it feels a bit strange. I really like the new colour of the windows, but i think the panel should be updated as well, maybe not to the exact same colour of the windows but to something closer. It seems like I'm using a different theme to each one, and it doesn't feel consistent anymore.

Images to compare:
![Captura de tela de 2021-12-18 20-27-15](https://user-images.githubusercontent.com/1660320/146658173-f1e5fadd-c76f-4118-955e-bb9cd0a2281e.png)
![Captura de tela de 2021-12-18 20-28-32](https://user-images.githubusercontent.com/1660320/146658175-d4f919ba-e498-40aa-972d-b7d35ed9b49c.png)

It's not a bug or anything like it, but i think it would be a really nice improvement.

Thank you again for this incredible job!

**Comment by Ethanol6** [comment]
I prefer the contrast but these colours are all defined by a few lines of CSS. I'd suggest making a custom theme and uploading it to https://cinnamon-spices.linuxmint.com so that anyone who prefers this could find it easily.

**Comment by enigma131** [comment]
Keep in mind Linux Mint is used on Laptop too with small screens. Have big headers is not a good thing in this situation, and having good contrast helps if you have multiples windows active.
