### ISSUE TITLE
release notes: update thingy screenshot

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint20.3-beta#55]
Thingy received shadows and LibreOffice support during the BETA.

**Comment by haggen88** [comment]
Office docs support is greatly appreciated!

@clefebvre after the update I noticed that the text/plain files appear in the 'LibreOffice Writer' category. At the moment I guess there are no plans to include them in a separate category, right?.

![thingy](https://user-images.githubusercontent.com/68134588/147112482-d5654168-b084-4f24-9026-696e9d48617d.png)

Regards

**Comment by clefebvre** [comment]
It's just a preview of what's planned for 21.. where we'll have proper app groups and configuration.

I could filter them out as a temporary solution though.
