### ISSUE TITLE
thingy ; Libreoffice writer files and text files are still a black image? 

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mint20.3-beta#58]
I received an update for thingy. 1.0.3
You guys are quick to work and I'm impressed that I should emulate you. 

Libreoffice writer files and text files are still a black image? 
It looks like it's still unfinished, right? 
![スクリーンショット 2021-12-21 16-24-37](https://user-images.githubusercontent.com/78515193/146890002-ccb22750-2064-4da8-9679-81ec6b542c7f.png)

**Comment by mtwebster** [comment]
This will be taken care of in the final iso, a thumbnailer will be included. You can try with:

```
apt install libgsf-bin
```
For the moment you'll need to navigate to where the files are with your file manager so thumbnails get generated, but then they should show up in thingy.
