### ISSUE TITLE
GIMP screenshot doesn't work right on Cinnamon

### ISSUE THREAD

**Issue by AlanTheLinuxGuy** [linuxmint/mint20.3-beta#59]
Gimp Version 2.10.18 installed from the Software Centre:

Take a screenshot of a single window does not offer the option to select a window but immediately takes a screenshot of the window that has the focus.

Select a region to grab returns an "Execution error" (screenshot attached
![gimp_error](https://user-images.githubusercontent.com/76230234/146974654-2b7f32c9-3ac0-4499-bc19-928c4f21c671.png)
)

**Comment by xenopeek** [comment]
This is about GIMP's screenshot function; in its menu select File > Create > Screenshot. On Linux Mint **20.3-beta Cinnamon** this functionality looks broken as compared to either Linux Mint **20.2 Cinnamon** or **20.3-beta MATE** (all with the same GIMP version installed). It may be an issue in the new Cinnamon version?

On **20.2 Cinnamon** an on **20.3-beta MATE** GIMP's screenshot dialog looks as below. After clicking "Snap" the mouse cursor changes to a large plus icon and a window can be clicked with it, causing GIMP to take a screenshot of that window's area.
![image](https://user-images.githubusercontent.com/21159972/146993053-123ab03a-91f2-4965-8771-1cc3e22d4870.png)

On **20.3-beta Cinnamon** GIMP's screenshot dialog looks decidedly different: **it's missing the Selection delay option** under Delay. (Again, on 20.3-beta MATE this does show.) After clicking "Snap" it immediately takes a screenshot of the GIMP window itself, not giving the user the mouse cursor to select a window with first.
![image](https://user-images.githubusercontent.com/21159972/146993724-fa25cdb6-9557-49d8-91f1-1d58dc2a9cd3.png)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/e52cdf216e7d30e99bb964862815dff42183dd94 fixes area selection.

Unfortunately, window selection is no longer available in Cinnamon, as the interface gimp is now using doesn't support this. The capture delay will need to be used to work around this.

edit: An alternate workaround is to use the system shortcut to snap a window to the clipboard (ctrl-alt-printscreen by default), then create->from clipboard in gimp.
