### ISSUE TITLE
flatpak: Update the Flatpak theme

### ISSUE THREAD

**Issue by Uldreth** [linuxmint/mint20.3-beta#6]
Description: The Mint-Y flatpak themes are still in the pre-20.3 state. This is less of a problem for server-side decorated windows (eg. Signal), but when an application using Gnome's client-side decorations (eg. Geary, Lollypop) is used, the application uses the previous version of the Mint-Y theme, thereby creating visual inconsistency.

Steps to reproduce:

1. Install a Flatpak-packaged application that uses Gnome/GTK CSD (eg. Lollypop).
2. Ensure that the relevant Mint-Y flatpak theme is autoinstalled, install it manually otherwise.
3. Open the application (eg. Lollypop), and also open a native/non-flatpak application (eg. Nemo or Gnome Disks).
4. Observe the visual inconsistency.

Expected results: Both applications should have an uniform theme.

Remarks: I do not have technical knowledge about the specifics of Flatpak packaging and theming, but I find it plausible this issue might be hard to fix. Both the new and the old theme occupy the same namespace (Mint-Y), and Flatpak themes need matching names. Therefore I find it likely that updating the flatpak theme would likewise break consistency for users sticking to pre-20.3 Mint. Perhaps the new theme could be renamed to eg. Mint-Z to ensure that it would peacefully coexist with its predecessor?

![lm_flatpak_theme](https://user-images.githubusercontent.com/29836149/145652505-aa6466f2-2db8-47b9-9265-ad8939ae90e2.png)

**Comment by LinuxOnTheDesktop** [comment]
> Perhaps the new theme could be renamed to eg. Mint-Z to ensure that it would peacefully coexist with its predecessor?

The people who dislike the new version of Mint-Y (because of its rounded corners, perhaps) would be pleased to have a choice; creating the new theme as 'Mint-Z' would give them that choice.

**Comment by haggen88** [comment]
@Uldreth  You mean this, right ?:

https://github.com/flathub/org.gtk.Gtk3theme.Mint-Y
https://github.com/flathub/org.gtk.Gtk3theme.Mint-Y-Dark
https://github.com/flathub/org.gtk.Gtk3theme.Mint-Y-Dark-Teal

**Comment by Uldreth** [comment]
@haggen88  Yes, those are the themes.
