### ISSUE TITLE
network-manager: WWAN setting connection problem

### ISSUE THREAD

**Issue by pawelnrg** [linuxmint/mint20.3-beta#61]
See network in light grey color (O2 because Giffgaff is virtual) when I try to configure connection it asking for network password (giffgaff don't have any) and can't connect (but under windows all working)

translation:
Komórkowe - Mobile

![obraz](https://user-images.githubusercontent.com/46251628/147221374-b7ab69ac-ca01-4080-ad9e-b0f18e776717.png)

**Comment by clefebvre** [comment]
This looks upstream to me.

Is that network-manager in MATE/Xfce?

**Comment by pawelnrg** [comment]
Is Xfce. Is not ;( as you see
![obraz](https://user-images.githubusercontent.com/46251628/147716375-ea2b9ca0-0e2d-473f-9090-30a0bf22dc57.png)
is only detected like for example Wi-Fi can't click, edit, ...
I do screen shot if You like.

**Comment by clefebvre** [comment]
Hi @pawelnrg, use the forums at https://forums.linuxmint.com/ to seek some help for this issue. I would suggest to check the security settings for this connection first.

If this is indeed a bug it will be upstream from us, since network-manager is maintained by Ubuntu directly.
