### ISSUE TITLE
Celluloid to exit when the celluloid dark theme is turned off? 

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mint20.3-beta#64]
Is it normal for celluloid to exit when the celluloid dark theme is turned off? 
![cinnamon-20211225-1](https://user-images.githubusercontent.com/78515193/147376258-0f3c1b1e-969d-4fd4-ac1f-2912b56233ed.gif)

**Comment by SebastJava** [comment]
CONFIRMED:

https://user-images.githubusercontent.com/31940713/147388963-6bedc9d2-f177-400d-aabb-77255ae6c817.mp4

And vice-versa: When I tried to set it back to dark=on, I got the same bug.

**Comment by clefebvre** [comment]
@SebastJava I can reproduce your issue as well. It's a Vbox rendering bug in my opinion, not something Celluloid can fix.

@vegam57 do you get a crash report in System Reports? You might want to check in there for a stack trace. If you have one I'd suggest to report this upstream to Celluloid directly. I suspect it might not be up to them though.... on real hardware here with Intel, neither issues are reproducible.

**Comment by vegam57** [comment]
This phenomenon is on an intel real machine.
![スクリーンショット 2021-12-27 21-29-52](https://user-images.githubusercontent.com/78515193/147472408-e6e73849-76f7-450e-87f3-0f13e3d5767b.png)
[code]
System:    Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.2.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: Latitude E6410 v: 0001 serial: <filter> Chassis: 
           type: 9 serial: <filter> 
           Mobo: Dell model: 04373Y v: A01 serial: <filter> BIOS: Dell v: A17 date: 05/12/2017 
Battery:   ID-1: BAT0 charge: 46.0 Wh condition: 46.0/48.8 Wh (94%) volts: 12.5/11.1 
           model: Samsung SDI DELL PT43699 serial: <filter> status: Full 
           Device-1: hidpp_battery_0 model: Logitech Wireless Mouse serial: <filter> 
           charge: 55% (should be ignored) status: Discharging 
CPU:       Topology: Dual Core model: Intel Core i5 M 520 bits: 64 type: MT MCP arch: Nehalem 
           rev: 5 L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19151 
           Speed: 1463 MHz min/max: 1199/2400 MHz Core speeds (MHz): 1: 1455 2: 1463 3: 1430 
           4: 1463 
Graphics:  Device-1: Intel Core Processor Integrated Graphics vendor: Dell Latitude E6410 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0046 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1280x800~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics (ILK) v: 2.1 Mesa 21.0.3 
           direct render: Yes 
Audio:     Device-1: Intel 5 Series/3400 Series High Definition Audio vendor: Dell Latitude E6410 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:3b56 
           Sound Server: ALSA v: k5.4.0-91-generic 
Network:   Device-1: Intel 82577LM Gigabit Network vendor: Dell Latitude E6410 driver: e1000e 
           v: 3.2.6-k port: 7040 bus ID: 00:19.0 chip ID: 8086:10ea 
           IF: eno1 state: down mac: <filter> 
           Device-2: Broadcom and subsidiaries BCM43224 802.11a/b/g/n 
           vendor: Dell Wireless 1520 Half-size Mini PCIe Card driver: bcma-pci-bridge v: N/A 
           port: 7000 bus ID: 02:00.0 chip ID: 14e4:4353 
           IF-ID-1: wlp2s0b1 state: up mac: <filter> 
Drives:    Local Storage: total: 114.80 GiB used: 10.15 GiB (8.8%) 
           ID-1: /dev/sda vendor: SanDisk model: SSD PLUS 120GB size: 111.80 GiB speed: 3.0 Gb/s 
           serial: <filter> 
           ID-2: /dev/sdb type: USB model: SafeNet eToken 7300 size: 3.00 GiB serial: <filter> 
Partition: ID-1: / size: 46.12 GiB used: 10.09 GiB (21.9%) fs: ext4 dev: /dev/sda6 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 1-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 
           chip ID: 8087:0020 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 2-1:2 info: Intel Integrated Rate Matching Hub ports: 8 rev: 2.0 
           chip ID: 8087:0020 
           Device-1: 2-1.3:3 info: Logitech Unifying Receiver type: Keyboard,Mouse 
           driver: logitech-djreceiver,usbhid rev: 2.0 chip ID: 046d:c534 
           Device-2: 2-1.4:4 info: Aladdin Knowledge Systems type: Smart Card,HID,Mass Storage 
           driver: hid-generic,usb-storage,usbhid rev: 2.0 chip ID: 0529:0602 
           Device-3: 2-1.8:5 info: Broadcom BCM5880 Secure Applications Processor type: Smart Card 
           driver: N/A rev: 1.1 chip ID: 0a5c:5800 
Sensors:   System Temperatures: cpu: 49.0 C mobo: N/A sodimm: 29.0 C 
           Fan Speeds (RPM): cpu: 0 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com una main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 225 Uptime: 11h 13m Memory: 5.73 GiB used: 1.56 GiB (27.2%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38 
[/code]
