### ISSUE TITLE
mate: panel 1.26 (wnck-applet) crash

### ISSUE THREAD

**Issue by MikeNavy** [linuxmint/mint20.3-beta#65]
Hi,
On Mate Github there are several reports about Mate panel 1.26 crashes, with wnck-applet involved: [https://github.com/mate-desktop/mate-panel/issues/1268](https://github.com/mate-desktop/mate-panel/issues/1268), [https://github.com/mate-desktop/mate-panel/issues/1246](https://github.com/mate-desktop/mate-panel/issues/1246).
This issue is not yet fixed, even in Mate panel 1.26.1 (latest release). 
Since this issue was not present in Mate panel 1.24 (I am a Linux Mint Mate 20.2 user), and since Mate panel 1.26 brings no new feature, I suggest to use Mate panel 1.24 in Mint Mate 20.3, at least until this crash issue is fixed.
Regards,
MN

**Comment by clefebvre** [comment]
mate-panel 1.26.1mint1 pushed to repositories.
Reverts:
c4a5e77 "wncklet: search the window before creating a new one"
06292db "wncklet: remove extra ref on gdk_x11_window_foreign_new_for_display"
