### ISSUE TITLE
Una Cinnamon - Minimized windows fail to despawn IF auto-hide panel true

### ISSUE THREAD

**Issue by Mr-Dead** [linuxmint/mint20.3-beta#66]
Hello.  This one should be easy to reproduce.  Problem observed with the installer (default settings yay) on two separate machines and mice.  

Expected Behavior: Active window should inactivate and exit display with proper effect after left-click titlebar minimize button.  

Observed Behavior:  Active window inactivates but fails to exit display after left-click titlebar minimize button.  Proper minimize effect is still observed, however.  The "ghost window" persists and obscures windows and desktop beneath.

Necessary conditions:  Only three have been found.
1. Panel Visibility set to "Auto-hide panel"
2. desktop-effects-minimize=traditional which is default
3. grouped-window-list@cinnamon,org installed AND window-list@cinnamon,org not installed, which is default.

Steps to reproduce:
1. boot up Una.  A usb installer will work.
2. Set panel visibility to "auto hide"
3. Open up a few windows.  Immediately after opening the last window, left-click titlebar minimize button.
4. Observe window-minimize effect, window inactivation, and display persistence.  The ghost of window past allows context menu of window beneath and obscures windows beneath.
![mini_uhoh](https://user-images.githubusercontent.com/2031616/147385954-e47b9ede-e09d-48fa-9972-b109903f25de.gif)
.

**Comment by mtwebster** [comment]
Can you check your `~/.xsession-errors` file when this happens?

I'm curious if you get this error:
```
(cinnamon:1340): Cjs-CRITICAL **: 13:58:01.371: JS ERROR: TypeError: this.scale is not a function
traditional@/usr/share/cinnamon/js/ui/windowEffects.js:226:18
_startWindowEffect@/usr/share/cinnamon/js/ui/windowManager.js:621:25
_minimizeWindow@/usr/share/cinnamon/js/ui/windowManager.js:680:14
WindowManager/<@/usr/share/cinnamon/js/ui/windowManager.js:505:66
```

I'm pretty certain this is fixed now:
https://github.com/linuxmint/cinnamon/commit/b33956a19b20c50d2df471b536499a72c0e152ab

There should be an update in the next day or two so you can confirm this.

**Comment by Mr-Dead** [comment]
Hello mtwebster.  I apologize for the delay.  Yes, I received similar error in ~/.xsession-errors as pasted below.  

```
(cinnamon:1631): Cjs-CRITICAL **: 20:01:44.014: JS ERROR: TypeError: this.scale is not a function
traditional@/usr/share/cinnamon/js/ui/windowEffects.js:226:18
_startWindowEffect@/usr/share/cinnamon/js/ui/windowManager.js:621:25
_minimizeWindow@/usr/share/cinnamon/js/ui/windowManager.js:680:14
WindowManager/<@/usr/share/cinnamon/js/ui/windowManager.js:505:66
```

Applying update Cinnamon 5.2.7+una appears to have resolved this issue.  Thank you!
