### ISSUE TITLE
Cinnamon blank screen under VirtualBox 6.1.26 with 3d acceleration turned on

### ISSUE THREAD

**Issue by DThiebaud** [linuxmint/mint20.3-beta#67]
In Cinnamon, running under VirtualBox 6.1.26 with 3d acceleration turned on, the whole screen except for the bottom bar is blank. Under the same configuration the screen works correctly on XFCE. To replicate, boot the install disk as a live CD.
Host system in LInux Mint Cinnamon 20.2, up to date.

**Comment by DThiebaud** [comment]
It worked correctly in Linux Mint Cinnamon 20.2.

**Comment by smurphos** [comment]
I've had no problem running the Cinnamon beta in Vbox 6.1.30 - for the virtual machine VMSVGA as graphic driver, 3D accel. ticked and Guest additions installed in the virtual machine.

**Comment by clefebvre** [comment]
Fixed in 6.1.28.
https://forums.linuxmint.com/viewtopic.php?p=2083873#p2083873
