### ISSUE TITLE
mate: screensaver bug

### ISSUE THREAD

**Issue by fblais** [linuxmint/mint20.3-beta#69]
Running the 20.3 MATE beta here.

I leave the computer alone for a while.
When I come back, sometimes, instead of seeing the screensaver (epicycle), the display is dimmed,
Very dimmed, I almost don't see anything.
The sole way to stop that is to logout/login. (not easy to see what you're doing when the display is so dimmed)
Sometimes the screensaver kicks in, other times, it's the display dimming.
The energy manager (gestionnaire d'énergie) is set to never put the computer or monitor in sleep mode.

Disabling the mate-screensaver stops the dimmed display from happening, so to me it confirms the bug.

Thanks.

**Comment by fblais** [comment]
FWIW:
I downloaded Mate-screensaver 1.26.1 source code and compiled it.
So far that problem didn't show up.
I'll update this thread in the next days.
But Mint MATE 20.3 may wish to ship with that version instead of 1.26.0.

Later,
François

**Comment by fblais** [comment]
1.26.1 still working great!

**Comment by clefebvre** [comment]
1.26.1 backported
