### ISSUE TITLE
mint-themes: Mint-Y metacity thumbnail outdated

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint20.3-beta#7]
For Cinnamon Edition, when going to change the window borders there is a difference now between the thumbnail graphic representation and the actual as shown in the screen capture.
![Screenshot-from-2021-12-10-21-21-48](https://user-images.githubusercontent.com/45599505/145660745-495a5b08-fc69-4a41-b768-20700b0554e6.png)

**Comment by WhosyVox** [comment]
Additional: toggling dark mode on in the Mintwelcome app results in the Mint-Y window border preview displaying as a solid grey when opening the Themes menu.

**Comment by enigma131** [comment]
Other bug here, for dark themes, no more possibility to put white windows color. In cinnamon github section, Clement gave me the trick to install legacy themes. New border have more hight than old one, its less fun on laptop...
https://github.com/linuxmint/cinnamon/issues/10525

**Comment by Secret-chest** [comment]
> Other bug here, for dark themes, no more possibility to put white windows color. In cinnamon github section, Clement gave me the trick to install legacy themes. New border have more hight than old one, its less fun on laptop...
> https://github.com/linuxmint/cinnamon/issues/10525

The trick will still work.

**Comment by hugok79** [comment]
> Additional: toggling dark mode on in the Mintwelcome app results in the Mint-Y window border preview displaying as a solid grey when opening the Themes menu.

https://github.com/linuxmint/mint20.3-beta/issues/19

**Comment by clefebvre** [comment]
Fixed in mint-themes 1.9.5
