### ISSUE TITLE
Nemo search error

### ISSUE THREAD

**Issue by Torok42** [linuxmint/mint20.3-beta#73]
Hello,
Problem in searching with tabs in file explorer
In the file explorer, open 2 tabs
To research
![image](https://user-images.githubusercontent.com/58152695/147713472-22a412b0-d53b-4718-962b-56cf4d17e618.png)

Go to the second tab
Return to the 1st tab
he searched item is in the text box below and it is disable
![image](https://user-images.githubusercontent.com/58152695/147713551-bd152e88-6e65-480c-b83a-bd27d2fe7daa.png)

If we click on the magnifying glass we are blocked
 
![image](https://user-images.githubusercontent.com/58152695/147713658-51aab3cb-0c5e-4e6a-95b1-d1c4d3d12e2f.png)

Thank you

**Comment by xenopeek** [comment]
I can reproduce this issue. Steps:

1. Open Nemo
2. Press Ctrl+T to open a second tab
3. Press Ctrl+F or looking glass to open search
4. In "Search for files" field type anything and press Enter to start the search
5. Switch to the other tab, and then back to the tab where you're searching
6. The text entered at step 4 in "Search for files" is copied to "Search content" field
7. Closing search doesn't clear the search, you're now stuck in this tab in search — tab needs closing to get out of search
