### ISSUE TITLE
mate: curious observation at the power management of the display

### ISSUE THREAD

**Issue by solaby** [linuxmint/mint20.3-beta#75]
Reproducing the problem is relatively easy. The problem existed also in the earlier versions of Linux Mint MATE. But probably the problem exists only in MATE, not in Cinnamon or Xfce. Although Ubuntu Mate 20.04.3 LTS has the same dialog, the problem does not show up there.

**Version:**
Linux Mint 20.3 “Una” MATE – BETA Release

**Expected behavior:**
The display does not turn off during inactivity.

**Observed behavior:**
The display turns off after 10 minutes of inactivity, even though the corresponding dialog in Power Management is set to "never".

**Required conditions:**
None, actually.

**Steps to reproduce:**

1. Boot linuxmint-20.3-mate-64bit-beta.iso in LIVE-Mode
2. Disable screensaver:
   Control Center > Screensaver
   Disable both options:
   - Activate screensaver when computer is idle
   - Lock screen when screensaver is active
3. Disable power management of the display:
Control Center > Power Management > On AC Power > Put display to sleep when inactive for
   - set to "never"
4. Close all opened windows.
Do not touch keyboard and mouse for 10 minutes

**Description:**
After 10 minutes, the screen will turn off. However, the screen should not turn off. All other options work correctly (1, 5, 10, 30, 60 minutes).

Thank you

**Comment by clefebvre** [comment]
I can't reproduce this. Neither can @monsta.
