### ISSUE TITLE
[Feature restoration request] Restore ms decay customization to Linux Mint 20.3 Cinnamon Beta's Effects

### ISSUE THREAD

**Issue by JohnAutodidact** [linuxmint/mint20.3-beta#76]
Subject OS: Linux Mint 20.3 Cinnamon Beta cum Linux Mint 20.3 Cinnamon.

Hardware tested: An Asus STRIX-GTX960-DC2OC-4GD5 with nVidia 495.44

Subject: Restoring the ms decay Customize portion of Linux Mint 20.2 Cinnamon's Effects to Linux Mint 20.3 Cinnamon's Effects.

An argument in favour of the above:

The ability to observe window and menu opening and closing transitions is not only subjectively pleasing to the eye, it also allows novice Linux Mint Cinnamon users to observe said transitions resulting from actions they take, as opposed to the somewhat jarring experience of having windows and menus appear and disappear in less than a blink of the eye.

More recent and performant graphics cards actually _need_ to have window and menu openings and closings slowed down a bit to mitigate the aforementioned jarring experience.

However, older yet still otherwise capable graphics cards, like the Asus STRIX-GTX960-DC2OC-4GD5 are inherently too slow for the default ms decay times currently employed in Linux Mint 20.3 Cinnamon Beta's Effects. Thus, the only mitigation available to them is turning the effects off thereby ceding the subjectively pleasing and quantifiably useful window and menu animations.

It is for the above reasons that, IMHO, a restoration of Linux Mint 20.2 Cinnamon's ms decay Effects Customize feature to Linux Mint 20.3 Cinnamon's Effects would be of benefit in allowing one to tailor the decay times of the various aspects of the Effects transitions to a much wider range of graphics cards in the service of enjoying a usefully pleasing, animated desktop.

As for the variety of effects types found in Linux Mint 20.2 Cinnamon's Effects? IMHO many of those are superfluous and likely add to the code burden in a needless manner. Thus, as a suggestion, they needn't be restored to Linux Mint 20.3 Cinnamon's Effects.

Thank you for your attention and consideration.

John

Pictured: The ms decay settings I use with Linux Mint 20.2 Cinnamon's Effects on an Asus STRIX-GTX960-DC2OC-4GD5 in order to achieve a performant, animated desktop.

![Linux Mint 20 2 Effects, Customize](https://user-images.githubusercontent.com/96786783/147794561-d67405c2-0906-4320-a2e3-a2743e60a443.png)

**Comment by clefebvre** [comment]
We can consider changing the default in a future release to make it longer. I'm not sure there's a need for it to be configurable though.
