### ISSUE TITLE
$PATH is incorrect - it contains /snap/bin

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/mint20.3-beta#77]
Loaded into a VM, Mint 20.3 beta [Cinnamon] has a path of:-
`echo $PATH`
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

I'd suggest it should be:-
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin (taken from LMDE4)

Note that **usrmerge** will have been applied (in both cases); certainly "snap" should not be encouraged.

**Comment by xenopeek** [comment]
The path `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin` is set like that in the file `/etc/environment`. No package owns that file? I don't know its origin.

Editing the `/etc/environment file, removing `:/snap/bin` from the PATH variable and then logging out and back in drops it from your PATH.

**Comment by haggen88** [comment]
There is still one package related to Snap in Mint: 'libsnapd-glib1' 
Could it be involved?

**Comment by WhosyVox** [comment]
Is there any harm keeping it? This seems like a rather silly point to me.

**Comment by xenopeek** [comment]
> There is still one package related to Snap in Mint: 'libsnapd-glib1'
> Could it be involved?

No. This is a very simple package; it doesn't include any pre- or post-install scripts to modify files like /etc/environment and only extracts a few files to /usr/. It's a library that PulseAudio from Ubuntu package base requires. Probably so if you do enable the snap store, snaps can have audio. Unrelated to this issue.

**Comment by Jeremy7701** [comment]
After the Mint team had finished stripping out all the snap rubbish, maybe the PATH reference was missed?
Happy to close this issue, as has been mentioned, it doesn't cause any problems.
