### ISSUE TITLE
xfce: panel 'Add to panel' behavior and added launcher behavior

### ISSUE THREAD

**Issue by Dadadot** [linuxmint/mint20.3-beta#80]
Version: Fully updated 20.3 Mint Beta
DE: Xfce4
Host: VirtualBox

The issues are almost exactly the same as in 20.2 (normal install, no virtual machine).
Adding a launcher (in this case google-chrome) adds a firefox launcher first before adding the actual selected launcher. Some of the pre-installed program-launchers show the same behavior but not all of them.
Removing launchers who show buggy behavior (i.e. firefox and chrome) crashes the panel. Sometimes just opening the right-click menu crashes the panel too.

A gif showing the behavior in the wild:
https://imgur.com/tnQerOf

Give some love to the mouse and thx for the great distro <3
Have a nice day!

**Comment by clefebvre** [comment]
I can't reproduce this issue. All added launchers work fine for me here, no FF is added.

There's definitely an issue, looking at your gif, but if I can't reproduce it I can't do much about it.. 

I can reproduce the crashes though. Looking upstream 4.16.3 fixes quite a few of them so I backported this version to 20.3.

That said, I'm still getting random crashes when removing launchers.

I'd suggest to take this upstream directly at https://gitlab.xfce.org/xfce/xfce4-panel/-/issues
