### ISSUE TITLE
mintupdate: Localization problem

### ISSUE THREAD

**Issue by muzena** [linuxmint/mint20.3-beta#81]
Update popup notification not localized/translated.
![update-notification2](https://user-images.githubusercontent.com/1978777/147876556-f9d2821a-3e09-4f89-8fc1-a05b76a8300d.png)

**Comment by clefebvre** [comment]
Can you paste the output of `locale`

**Comment by muzena** [comment]
@clefebvre 
> mint@mint-X470-AORUS-ULTRA-GAMING:~$ locale
LANG=hr_HR.UTF-8
LANGUAGE=hr
LC_CTYPE="hr_HR.UTF-8"
LC_NUMERIC="hr_HR.UTF-8"
LC_TIME="hr_HR.UTF-8"
LC_COLLATE="hr_HR.UTF-8"
LC_MONETARY="hr_HR.UTF-8"
LC_MESSAGES="hr_HR.UTF-8"
LC_PAPER="hr_HR.UTF-8"
LC_NAME="hr_HR.UTF-8"
LC_ADDRESS="hr_HR.UTF-8"
LC_TELEPHONE="hr_HR.UTF-8"
LC_MEASUREMENT="hr_HR.UTF-8"
LC_IDENTIFICATION="hr_HR.UTF-8"
LC_ALL=

**Comment by clefebvre** [comment]
and `apt version mintupdate`

**Comment by clefebvre** [comment]
Translations for this in Croatian came in 5.8.0.

**Comment by muzena** [comment]
Now I upgrade on 5.8.1 version.
Can this message be launched from the terminal, or I will check again in 2 days.

**Comment by clefebvre** [comment]
What version did you have before?

**Comment by muzena** [comment]
I think 5.8.0

**Comment by clefebvre** [comment]
![image](https://user-images.githubusercontent.com/1138515/147932403-c500615f-cdfc-4e89-af76-8cc2c0fec3b3.png)
