### ISSUE TITLE
[request] Keep Mint 20.2 window borders as an optional theme

### ISSUE THREAD

**Issue by WhosyVox** [linuxmint/mint20.3-beta#9]
As the title implies, the suggestion is simple: Keep the older Mint 20.2 squared window borders as an additional theme. Be it pre-installed, added to the third-party themes repository, etc.

I don't ask it be set as default, either for new installations or upgrades, but simply a choice for the user.

I understand the intention behind the new change but I don't find it's aesthetics all too pleasing. I'm sure this will be a sticking point for others; having it tackled pre-release rather than post-release tends to result in far less friction.

Edit:
I've been made aware of the `mint-themes-legacy` apt package. This should probably be pre-installed in the ISO, and of-course fixed for dark mode. But it's nice to know that was already in place! :)

**Comment by LinuxOnTheDesktop** [comment]
Others have made the same request - [here](https://github.com/linuxmint/mint20.3-beta/issues/8#issuecomment-991425560) and [here](https://github.com/linuxmint/mint20.3-beta/issues/6#issuecomment-991395572). But, ah, there is, already, the mint-themes-legacy package; that is something.

**Comment by haggen88** [comment]
Keeping the Mint-Y-legacy theme pre-installed may help to solve some eventual problems for users upgrading to Mint 20.3. 
Many users tweak the look and feel of Cinnamon, and perhaps the lack of the current Mint-Y theme will cause inconvenience.

**Comment by Jildridge** [comment]
In that respect I would like to ask if it is maybe possible to implement an option to distinguish between active and inactive windows by different colouring of the title bar.
Below you find a suggestion I fiddled around with the simple mint-y theme of 20.2.
![windowdiff](https://user-images.githubusercontent.com/42801814/145873302-e4821336-48f7-484d-ba89-8691effbe5d1.png)

**Comment by OdinVex** [comment]
I would like to see `mint-themes-legacy` *always* installed on every release...*sigh* I don't like rounded borders. ...Borders are so freaking thick now...*bigger sigh*

**Comment by masemoel** [comment]
Borders would be fine if they were applied in the bottom corners as well, and not only in the top corners 😅

**Comment by clefebvre** [comment]
mint-themes-legacy provides this functionality.
